version: '3.8'
services:
  nodejs:
    image: transcendence/frontend
    container_name: transcendence_frontend
    build:
      context: app/frontend/
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./app/frontend/public:/home/transcendence/public