version: '3.8'
services:
  frontend:
    image: transcendence/frontend
    container_name: transcendence_frontend
    build:
      context: app/frontend/
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./app/frontend/public:/home/transcendence/public
  backend:
    image: transcendence/backend
    container_name: transcendence_backend
    build:
      context: app/backend/
      dockerfile: Dockerfile
    ports:
      - "81:80"
    volumes:
      - ./app/backend/src:/home/transcendence/src