version: '3.8'
services:
  nodejs:
    image: transcendence/nginx
    container_name: nginx
    build:
      context: app/frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./app/frontend:/home/transcendence